sudo: required

language: go
go:
    - 1.6
    - tip

services:
    - docker

env:
    global:
        - DOCKER_VERSION=1.10.1-0~trusty

script:
    - docker version
    - go get
    - go build
    - ./hmake all test e2e -sv
